-- MySQL Script generated by MySQL Workbench
-- 08/29/18 15:18:58
-- Model: DER_Radiko    Version: 1.0

-- Base de datos de Rádiko

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema radiko_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema radiko_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `radiko_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `radiko_db` ;

-- -----------------------------------------------------
-- Table `radiko_db`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiko_db`.`USUARIOS` (
  `id_usuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `fecha_alta` DATETIME NOT NULL,
  `estado` ENUM('activo','suspendido','dado de baja','pendiente de pago') NOT NULL,
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC),
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiko_db`.`ADMINISTRADORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiko_db`.`ADMINISTRADORES` (
  `fk_usuario` INT UNSIGNED NOT NULL,
  INDEX `fk_ADMINISTRADORES_USUARIOS_idx` (`fk_usuario` ASC),
  PRIMARY KEY (`fk_usuario`),
  CONSTRAINT `fk_ADMINISTRADORES_USUARIOS`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `radiko_db`.`USUARIOS` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiko_db`.`BARRIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiko_db`.`BARRIOS` (
  `id_barrio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `barrio` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_barrio`),
  UNIQUE INDEX `barrio_UNIQUE` (`barrio` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiko_db`.`DIRECCIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiko_db`.`DIRECCIONES` (
  `id_direccion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `referencia` VARCHAR(50) NULL,
  `calle` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `piso` VARCHAR(10) NULL,
  `departamento` VARCHAR(10) NULL,
  `telefono` INT NULL,
  `aclaracion` VARCHAR(255) NULL,
  `tipo` BIT NOT NULL,
  `fk_barrio` INT NOT NULL,
  PRIMARY KEY (`id_direccion`),
  INDEX `fk_DIRECCIONES_BARRIOS1_idx` (`fk_barrio` ASC),
  CONSTRAINT `fk_DIRECCIONES_BARRIOS1`
    FOREIGN KEY (`fk_barrio`)
    REFERENCES `radiko_db`.`BARRIOS` (`id_barrio`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiko_db`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiko_db`.`CLIENTES` (
  `fk_usuario` INT UNSIGNED NOT NULL,
  `dni` INT(8) NULL,
  `fecha_nac` DATE NULL,
  `fk_direccion` INT NOT NULL,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC),
  INDEX `fk_CLIENTES_USUARIOS1_idx` (`fk_usuario` ASC),
  INDEX `fk_CLIENTES_DIRECCIONES1_idx` (`fk_direccion` ASC),
  PRIMARY KEY (`fk_usuario`),
  CONSTRAINT `fk_CLIENTES_USUARIOS1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `radiko_db`.`USUARIOS` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_CLIENTES_DIRECCIONES1`
    FOREIGN KEY (`fk_direccion`)
    REFERENCES `radiko_db`.`DIRECCIONES` (`id_direccion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'El ID no es autoincrementable';


-- -----------------------------------------------------
-- Table `radiko_db`.`TIPO_HUERTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiko_db`.`TIPO_HUERTA` (
  `id_tipo_huerta` TINYINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_huerta`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiko_db`.`HUERTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiko_db`.`HUERTAS` (
  `fk_usuario` INT UNSIGNED NOT NULL,
  `cuit` INT(11) UNSIGNED NOT NULL,
  `razon_social` VARCHAR(100) NULL,
  `direccion` VARCHAR(50) NULL,
  `telefono` INT UNSIGNED NULL,
  `cantidad_max_envios` TINYINT(255) UNSIGNED NULL,
  `fk_tipo_huerta` TINYINT(2) NOT NULL,
  UNIQUE INDEX `cuit_UNIQUE` (`cuit` ASC),
  INDEX `fk_HUERTAS_USUARIOS1_idx` (`fk_usuario` ASC),
  INDEX `fk_HUERTAS_TIPO_HUERTA1_idx` (`fk_tipo_huerta` ASC),
  PRIMARY KEY (`fk_usuario`),
  CONSTRAINT `fk_HUERTAS_USUARIOS1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `radiko_db`.`USUARIOS` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_HUERTAS_TIPO_HUERTA1`
    FOREIGN KEY (`fk_tipo_huerta`)
    REFERENCES `radiko_db`.`TIPO_HUERTA` (`id_tipo_huerta`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiko_db`.`CATEGORIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiko_db`.`CATEGORIAS` (
  `id_categoria` TINYINT(2) UNSIGNED NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `descripcion` TEXT(1000) NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `categoria_UNIQUE` (`categoria` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiko_db`.`UNIDADES_DE_MEDIDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiko_db`.`UNIDADES_DE_MEDIDA` (
  `id_unidad_medida` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `unidad_de_medida` VARCHAR(45) NULL,
  PRIMARY KEY (`id_unidad_medida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiko_db`.`PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiko_db`.`PRODUCTOS` (
  `id_producto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(100) NOT NULL,
  `descripcion` TEXT(1000) NULL,
  `marca` VARCHAR(45) NULL,
  `precio` FLOAT(6,2) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `stock` INT NOT NULL,
  `estado` BIT NULL,
  `fecha_alta` DATETIME NOT NULL,
  `fecha_baja` DATETIME NOT NULL,
  `fk_categoria` TINYINT(2) NOT NULL,
  `fk_unidad_medida` INT NOT NULL,
  `HUERTAS_fk_usuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_PRODUCTOS_CATEGORIAS1_idx` (`fk_categoria` ASC),
  INDEX `fk_PRODUCTOS_UNIDADES_DE_MEDIDA1_idx` (`fk_unidad_medida` ASC),
  INDEX `fk_PRODUCTOS_HUERTAS1_idx` (`HUERTAS_fk_usuario` ASC),
  CONSTRAINT `fk_PRODUCTOS_CATEGORIAS1`
    FOREIGN KEY (`fk_categoria`)
    REFERENCES `radiko_db`.`CATEGORIAS` (`id_categoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PRODUCTOS_UNIDADES_DE_MEDIDA1`
    FOREIGN KEY (`fk_unidad_medida`)
    REFERENCES `radiko_db`.`UNIDADES_DE_MEDIDA` (`id_unidad_medida`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PRODUCTOS_HUERTAS1`
    FOREIGN KEY (`HUERTAS_fk_usuario`)
    REFERENCES `radiko_db`.`HUERTAS` (`fk_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiko_db`.`TIPO_PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiko_db`.`TIPO_PAGO` (
  `id_tipo_pago` TINYINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_pago` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_tipo_pago`),
  UNIQUE INDEX `tipo_pago_UNIQUE` (`tipo_pago` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiko_db`.`ESTADO_PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiko_db`.`ESTADO_PEDIDO` (
  `id_estado` TINYINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado`),
  UNIQUE INDEX `estado_UNIQUE` (`estado` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiko_db`.`ENVIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiko_db`.`ENVIO` (
  `id_envio` INT UNSIGNED NOT NULL,
  `costo_envio` VARCHAR(45) NULL,
  `fecha_envio` DATETIME NOT NULL,
  `fk_direccion` INT NOT NULL,
  PRIMARY KEY (`id_envio`),
  INDEX `fk_ENVIO_DIRECCIONES1_idx` (`fk_direccion` ASC),
  CONSTRAINT `fk_ENVIO_DIRECCIONES1`
    FOREIGN KEY (`fk_direccion`)
    REFERENCES `radiko_db`.`DIRECCIONES` (`id_direccion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiko_db`.`DISPONIBILIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiko_db`.`DISPONIBILIDAD` (
  `id_disponibilidad` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dias` SET('lunes','martes','miercoles','jueves','viernes','sabado','domingo') NOT NULL,
  `horario_inicio` TIME NOT NULL,
  `horario_final` TIME NOT NULL,
  `HUERTAS_fk_usuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_disponibilidad`),
  INDEX `fk_DISPONIBILIDAD_HUERTAS1_idx` (`HUERTAS_fk_usuario` ASC),
  CONSTRAINT `fk_DISPONIBILIDAD_HUERTAS1`
    FOREIGN KEY (`HUERTAS_fk_usuario`)
    REFERENCES `radiko_db`.`HUERTAS` (`fk_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiko_db`.`PEDIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiko_db`.`PEDIDOS` (
  `id_pedido` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_pedido` DATETIME NOT NULL,
  `subtotal` FLOAT(8,2) NOT NULL,
  `total` FLOAT(8,2) NOT NULL,
  `observaciones` TEXT(1000) NULL,
  `fk_tipo_pago` TINYINT(2) NOT NULL,
  `fk_estado_pedido` TINYINT(2) NOT NULL,
  `fk_envio` INT NOT NULL,
  `fk_disponibilidad` INT NOT NULL,
  `CLIENTES_fk_usuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_PEDIDOS_TIPO_PAGO1_idx` (`fk_tipo_pago` ASC),
  INDEX `fk_PEDIDOS_ESTADO_PEDIDO1_idx` (`fk_estado_pedido` ASC),
  INDEX `fk_PEDIDOS_ENVIO1_idx` (`fk_envio` ASC),
  INDEX `fk_PEDIDOS_DISPONIBILIDAD1_idx` (`fk_disponibilidad` ASC),
  INDEX `fk_PEDIDOS_CLIENTES1_idx` (`CLIENTES_fk_usuario` ASC),
  CONSTRAINT `fk_PEDIDOS_TIPO_PAGO1`
    FOREIGN KEY (`fk_tipo_pago`)
    REFERENCES `radiko_db`.`TIPO_PAGO` (`id_tipo_pago`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PEDIDOS_ESTADO_PEDIDO1`
    FOREIGN KEY (`fk_estado_pedido`)
    REFERENCES `radiko_db`.`ESTADO_PEDIDO` (`id_estado`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PEDIDOS_ENVIO1`
    FOREIGN KEY (`fk_envio`)
    REFERENCES `radiko_db`.`ENVIO` (`id_envio`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PEDIDOS_DISPONIBILIDAD1`
    FOREIGN KEY (`fk_disponibilidad`)
    REFERENCES `radiko_db`.`DISPONIBILIDAD` (`id_disponibilidad`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PEDIDOS_CLIENTES1`
    FOREIGN KEY (`CLIENTES_fk_usuario`)
    REFERENCES `radiko_db`.`CLIENTES` (`fk_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiko_db`.`REL_PEDIDOS_PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiko_db`.`REL_PEDIDOS_PRODUCTOS` (
  `PEDIDOS_id_pedido` INT NOT NULL,
  `PRODUCTOS_id_producto` INT NOT NULL,
  `precio` FLOAT(6,2) NOT NULL,
  `cantidad` TINYINT(2) NOT NULL,
  PRIMARY KEY (`PEDIDOS_id_pedido`, `PRODUCTOS_id_producto`),
  INDEX `fk_PEDIDOS_has_PRODUCTOS_PRODUCTOS1_idx` (`PRODUCTOS_id_producto` ASC),
  INDEX `fk_PEDIDOS_has_PRODUCTOS_PEDIDOS1_idx` (`PEDIDOS_id_pedido` ASC),
  CONSTRAINT `fk_PEDIDOS_has_PRODUCTOS_PEDIDOS1`
    FOREIGN KEY (`PEDIDOS_id_pedido`)
    REFERENCES `radiko_db`.`PEDIDOS` (`id_pedido`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PEDIDOS_has_PRODUCTOS_PRODUCTOS1`
    FOREIGN KEY (`PRODUCTOS_id_producto`)
    REFERENCES `radiko_db`.`PRODUCTOS` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiko_db`.`LOG_EVENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiko_db`.`LOG_EVENTOS` (
  `id_log_eventos` INT NOT NULL AUTO_INCREMENT,
  `accion` VARCHAR(255) NOT NULL,
  `ip` VARCHAR(45) NOT NULL,
  `fecha_evento` DATETIME NOT NULL,
  `USUARIOS_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_log_eventos`),
  INDEX `fk_LOG_EVENTOS_USUARIOS1_idx` (`USUARIOS_id_usuario` ASC),
  CONSTRAINT `fk_LOG_EVENTOS_USUARIOS1`
    FOREIGN KEY (`USUARIOS_id_usuario`)
    REFERENCES `radiko_db`.`USUARIOS` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `radiko_db`.`REL_HUERTAS_CLIENTES_REVIEW`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `radiko_db`.`REL_HUERTAS_CLIENTES_REVIEW` (
  `HUERTAS_fk_usuario` INT UNSIGNED NOT NULL,
  `CLIENTES_fk_usuario` INT UNSIGNED NOT NULL,
  `estrellas` TINYINT(1) NULL,
  `comentario` TEXT(1000) NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`HUERTAS_fk_usuario`, `CLIENTES_fk_usuario`),
  INDEX `fk_HUERTAS_has_CLIENTES1_CLIENTES1_idx` (`CLIENTES_fk_usuario` ASC),
  INDEX `fk_HUERTAS_has_CLIENTES1_HUERTAS1_idx` (`HUERTAS_fk_usuario` ASC),
  CONSTRAINT `fk_HUERTAS_has_CLIENTES1_HUERTAS1`
    FOREIGN KEY (`HUERTAS_fk_usuario`)
    REFERENCES `radiko_db`.`HUERTAS` (`fk_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_HUERTAS_has_CLIENTES1_CLIENTES1`
    FOREIGN KEY (`CLIENTES_fk_usuario`)
    REFERENCES `radiko_db`.`CLIENTES` (`fk_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
